name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
      - '**'  # Поддержка всех веток

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download PlantUML
        run: |
          mkdir -p ~/plantuml
          wget -O ~/plantuml/plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2023.12/plantuml.jar

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinxcontrib-plantuml sphinx-rtd-theme

      - name: Build documentation
        run: |
          cd docs
          echo "plantuml = 'java -jar ~/plantuml/plantuml.jar'" >> source/conf.py
          echo "html_theme = 'sphinx_rtd_theme'" >> source/conf.py
          make clean
          make html
          touch _build/html/.nojekyll  # Важно!

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html