name: Проверка PlantUML и Graphviz

on: [push]

jobs:
  check-plantuml-graphviz:
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Клонируем репозиторий
        uses: actions/checkout@v3

      - name: ☕ Устанавливаем Java и Graphviz (нужна для PlantUML)
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre graphviz

      - name: 🌿 Скачиваем последнюю версию PlantUML
        run: |
          # Создаем папку для PlantUML в /usr/local/bin, скачиваем PlantUML
          sudo mkdir -p /usr/local/bin/plantuml
          sudo wget -q https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar -O /usr/local/bin/plantuml/plantuml.jar
          # Проверяем версию PlantUML
          java -jar /usr/local/bin/plantuml/plantuml.jar -version

      - name: Проверка Graphviz и Dot через PlantUML
        run: |
          # Проверяем установку Graphviz (dot)
          dot -V
          # Проверка, что Graphviz работает с PlantUML
          java -jar /usr/local/bin/plantuml/plantuml.jar -testdot
